//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEscritorio.WSServicios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfVehiculo", Namespace="http://tempuri.org/", ItemName="vehiculo")]
    [System.SerializableAttribute()]
    public class ArrayOfVehiculo : System.Collections.Generic.List<AppEscritorio.WSServicios.vehiculo> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vehiculo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class vehiculo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GSNombreField;
        
        private int GSAnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GSPrestacionesField;
        
        private bool GSDisponibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GSColorField;
        
        private int GSPuertasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GSCombustibleField;
        
        private int GSValoracionField;
        
        private double GSPrecioField;
        
        private int GSIdVehiculoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GSNombre {
            get {
                return this.GSNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.GSNombreField, value) != true)) {
                    this.GSNombreField = value;
                    this.RaisePropertyChanged("GSNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int GSAno {
            get {
                return this.GSAnoField;
            }
            set {
                if ((this.GSAnoField.Equals(value) != true)) {
                    this.GSAnoField = value;
                    this.RaisePropertyChanged("GSAno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string GSPrestaciones {
            get {
                return this.GSPrestacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.GSPrestacionesField, value) != true)) {
                    this.GSPrestacionesField = value;
                    this.RaisePropertyChanged("GSPrestaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool GSDisponible {
            get {
                return this.GSDisponibleField;
            }
            set {
                if ((this.GSDisponibleField.Equals(value) != true)) {
                    this.GSDisponibleField = value;
                    this.RaisePropertyChanged("GSDisponible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string GSColor {
            get {
                return this.GSColorField;
            }
            set {
                if ((object.ReferenceEquals(this.GSColorField, value) != true)) {
                    this.GSColorField = value;
                    this.RaisePropertyChanged("GSColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int GSPuertas {
            get {
                return this.GSPuertasField;
            }
            set {
                if ((this.GSPuertasField.Equals(value) != true)) {
                    this.GSPuertasField = value;
                    this.RaisePropertyChanged("GSPuertas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string GSCombustible {
            get {
                return this.GSCombustibleField;
            }
            set {
                if ((object.ReferenceEquals(this.GSCombustibleField, value) != true)) {
                    this.GSCombustibleField = value;
                    this.RaisePropertyChanged("GSCombustible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int GSValoracion {
            get {
                return this.GSValoracionField;
            }
            set {
                if ((this.GSValoracionField.Equals(value) != true)) {
                    this.GSValoracionField = value;
                    this.RaisePropertyChanged("GSValoracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public double GSPrecio {
            get {
                return this.GSPrecioField;
            }
            set {
                if ((this.GSPrecioField.Equals(value) != true)) {
                    this.GSPrecioField = value;
                    this.RaisePropertyChanged("GSPrecio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int GSIdVehiculo {
            get {
                return this.GSIdVehiculoField;
            }
            set {
                if ((this.GSIdVehiculoField.Equals(value) != true)) {
                    this.GSIdVehiculoField = value;
                    this.RaisePropertyChanged("GSIdVehiculo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAlquilan", Namespace="http://tempuri.org/", ItemName="alquilan")]
    [System.SerializableAttribute()]
    public class ArrayOfAlquilan : System.Collections.Generic.List<AppEscritorio.WSServicios.alquilan> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="alquilan", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class alquilan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int GSidCocheField;
        
        private int GSidUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GSfAlquilerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GSfFinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int GSidCoche {
            get {
                return this.GSidCocheField;
            }
            set {
                if ((this.GSidCocheField.Equals(value) != true)) {
                    this.GSidCocheField = value;
                    this.RaisePropertyChanged("GSidCoche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int GSidUsuario {
            get {
                return this.GSidUsuarioField;
            }
            set {
                if ((this.GSidUsuarioField.Equals(value) != true)) {
                    this.GSidUsuarioField = value;
                    this.RaisePropertyChanged("GSidUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string GSfAlquiler {
            get {
                return this.GSfAlquilerField;
            }
            set {
                if ((object.ReferenceEquals(this.GSfAlquilerField, value) != true)) {
                    this.GSfAlquilerField = value;
                    this.RaisePropertyChanged("GSfAlquiler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string GSfFin {
            get {
                return this.GSfFinField;
            }
            set {
                if ((object.ReferenceEquals(this.GSfFinField, value) != true)) {
                    this.GSfFinField = value;
                    this.RaisePropertyChanged("GSfFin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GSNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GSApellidosField;
        
        private int GSEdadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GSUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GSPassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GSTipoField;
        
        private int GSIdUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GSNombre {
            get {
                return this.GSNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.GSNombreField, value) != true)) {
                    this.GSNombreField = value;
                    this.RaisePropertyChanged("GSNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string GSApellidos {
            get {
                return this.GSApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.GSApellidosField, value) != true)) {
                    this.GSApellidosField = value;
                    this.RaisePropertyChanged("GSApellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int GSEdad {
            get {
                return this.GSEdadField;
            }
            set {
                if ((this.GSEdadField.Equals(value) != true)) {
                    this.GSEdadField = value;
                    this.RaisePropertyChanged("GSEdad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string GSUser {
            get {
                return this.GSUserField;
            }
            set {
                if ((object.ReferenceEquals(this.GSUserField, value) != true)) {
                    this.GSUserField = value;
                    this.RaisePropertyChanged("GSUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string GSPass {
            get {
                return this.GSPassField;
            }
            set {
                if ((object.ReferenceEquals(this.GSPassField, value) != true)) {
                    this.GSPassField = value;
                    this.RaisePropertyChanged("GSPass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string GSTipo {
            get {
                return this.GSTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.GSTipoField, value) != true)) {
                    this.GSTipoField = value;
                    this.RaisePropertyChanged("GSTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int GSIdUsuario {
            get {
                return this.GSIdUsuarioField;
            }
            set {
                if ((this.GSIdUsuarioField.Equals(value) != true)) {
                    this.GSIdUsuarioField = value;
                    this.RaisePropertyChanged("GSIdUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSServicios.serviciosSoap")]
    public interface serviciosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSRegistrarUsuario", ReplyAction="*")]
        AppEscritorio.WSServicios.WSRegistrarUsuarioResponse WSRegistrarUsuario(AppEscritorio.WSServicios.WSRegistrarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSRegistrarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSRegistrarUsuarioResponse> WSRegistrarUsuarioAsync(AppEscritorio.WSServicios.WSRegistrarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSLogin", ReplyAction="*")]
        AppEscritorio.WSServicios.WSLoginResponse WSLogin(AppEscritorio.WSServicios.WSLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSLoginResponse> WSLoginAsync(AppEscritorio.WSServicios.WSLoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento WSMostrarVehiculosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSMostrarVehiculos", ReplyAction="*")]
        AppEscritorio.WSServicios.WSMostrarVehiculosResponse WSMostrarVehiculos(AppEscritorio.WSServicios.WSMostrarVehiculosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSMostrarVehiculos", ReplyAction="*")]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSMostrarVehiculosResponse> WSMostrarVehiculosAsync(AppEscritorio.WSServicios.WSMostrarVehiculosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento WSMostrarVehiculoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSMostrarVehiculo", ReplyAction="*")]
        AppEscritorio.WSServicios.WSMostrarVehiculoResponse WSMostrarVehiculo(AppEscritorio.WSServicios.WSMostrarVehiculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSMostrarVehiculo", ReplyAction="*")]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSMostrarVehiculoResponse> WSMostrarVehiculoAsync(AppEscritorio.WSServicios.WSMostrarVehiculoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fa del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSAlquilarCoche", ReplyAction="*")]
        AppEscritorio.WSServicios.WSAlquilarCocheResponse WSAlquilarCoche(AppEscritorio.WSServicios.WSAlquilarCocheRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSAlquilarCoche", ReplyAction="*")]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSAlquilarCocheResponse> WSAlquilarCocheAsync(AppEscritorio.WSServicios.WSAlquilarCocheRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento WSMostrarAlquileresResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSMostrarAlquileres", ReplyAction="*")]
        AppEscritorio.WSServicios.WSMostrarAlquileresResponse WSMostrarAlquileres(AppEscritorio.WSServicios.WSMostrarAlquileresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSMostrarAlquileres", ReplyAction="*")]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSMostrarAlquileresResponse> WSMostrarAlquileresAsync(AppEscritorio.WSServicios.WSMostrarAlquileresRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento modelo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSBuscarVehiculos", ReplyAction="*")]
        AppEscritorio.WSServicios.WSBuscarVehiculosResponse WSBuscarVehiculos(AppEscritorio.WSServicios.WSBuscarVehiculosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSBuscarVehiculos", ReplyAction="*")]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSBuscarVehiculosResponse> WSBuscarVehiculosAsync(AppEscritorio.WSServicios.WSBuscarVehiculosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSBuscarUsuario", ReplyAction="*")]
        AppEscritorio.WSServicios.WSBuscarUsuarioResponse WSBuscarUsuario(AppEscritorio.WSServicios.WSBuscarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSBuscarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSBuscarUsuarioResponse> WSBuscarUsuarioAsync(AppEscritorio.WSServicios.WSBuscarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSguardarCochesXML", ReplyAction="*")]
        void WSguardarCochesXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSguardarCochesXML", ReplyAction="*")]
        System.Threading.Tasks.Task WSguardarCochesXMLAsync();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fileName del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSguardarCochesBD", ReplyAction="*")]
        AppEscritorio.WSServicios.WSguardarCochesBDResponse WSguardarCochesBD(AppEscritorio.WSServicios.WSguardarCochesBDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSguardarCochesBD", ReplyAction="*")]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSguardarCochesBDResponse> WSguardarCochesBDAsync(AppEscritorio.WSServicios.WSguardarCochesBDRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento modelo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSGuardarVehiculo", ReplyAction="*")]
        AppEscritorio.WSServicios.WSGuardarVehiculoResponse WSGuardarVehiculo(AppEscritorio.WSServicios.WSGuardarVehiculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSGuardarVehiculo", ReplyAction="*")]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSGuardarVehiculoResponse> WSGuardarVehiculoAsync(AppEscritorio.WSServicios.WSGuardarVehiculoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSRegistrarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSRegistrarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSRegistrarUsuarioRequestBody Body;
        
        public WSRegistrarUsuarioRequest() {
        }
        
        public WSRegistrarUsuarioRequest(AppEscritorio.WSServicios.WSRegistrarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSRegistrarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int edad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pass;
        
        public WSRegistrarUsuarioRequestBody() {
        }
        
        public WSRegistrarUsuarioRequestBody(string nombre, string apellidos, int edad, string user, string pass) {
            this.nombre = nombre;
            this.apellidos = apellidos;
            this.edad = edad;
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSRegistrarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSRegistrarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSRegistrarUsuarioResponseBody Body;
        
        public WSRegistrarUsuarioResponse() {
        }
        
        public WSRegistrarUsuarioResponse(AppEscritorio.WSServicios.WSRegistrarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class WSRegistrarUsuarioResponseBody {
        
        public WSRegistrarUsuarioResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSLogin", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSLoginRequestBody Body;
        
        public WSLoginRequest() {
        }
        
        public WSLoginRequest(AppEscritorio.WSServicios.WSLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public WSLoginRequestBody() {
        }
        
        public WSLoginRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSLoginResponseBody Body;
        
        public WSLoginResponse() {
        }
        
        public WSLoginResponse(AppEscritorio.WSServicios.WSLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int WSLoginResult;
        
        public WSLoginResponseBody() {
        }
        
        public WSLoginResponseBody(int WSLoginResult) {
            this.WSLoginResult = WSLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSMostrarVehiculosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSMostrarVehiculos", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSMostrarVehiculosRequestBody Body;
        
        public WSMostrarVehiculosRequest() {
        }
        
        public WSMostrarVehiculosRequest(AppEscritorio.WSServicios.WSMostrarVehiculosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class WSMostrarVehiculosRequestBody {
        
        public WSMostrarVehiculosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSMostrarVehiculosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSMostrarVehiculosResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSMostrarVehiculosResponseBody Body;
        
        public WSMostrarVehiculosResponse() {
        }
        
        public WSMostrarVehiculosResponse(AppEscritorio.WSServicios.WSMostrarVehiculosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSMostrarVehiculosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppEscritorio.WSServicios.ArrayOfVehiculo WSMostrarVehiculosResult;
        
        public WSMostrarVehiculosResponseBody() {
        }
        
        public WSMostrarVehiculosResponseBody(AppEscritorio.WSServicios.ArrayOfVehiculo WSMostrarVehiculosResult) {
            this.WSMostrarVehiculosResult = WSMostrarVehiculosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSMostrarVehiculoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSMostrarVehiculo", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSMostrarVehiculoRequestBody Body;
        
        public WSMostrarVehiculoRequest() {
        }
        
        public WSMostrarVehiculoRequest(AppEscritorio.WSServicios.WSMostrarVehiculoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSMostrarVehiculoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idv;
        
        public WSMostrarVehiculoRequestBody() {
        }
        
        public WSMostrarVehiculoRequestBody(int idv) {
            this.idv = idv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSMostrarVehiculoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSMostrarVehiculoResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSMostrarVehiculoResponseBody Body;
        
        public WSMostrarVehiculoResponse() {
        }
        
        public WSMostrarVehiculoResponse(AppEscritorio.WSServicios.WSMostrarVehiculoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSMostrarVehiculoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppEscritorio.WSServicios.vehiculo WSMostrarVehiculoResult;
        
        public WSMostrarVehiculoResponseBody() {
        }
        
        public WSMostrarVehiculoResponseBody(AppEscritorio.WSServicios.vehiculo WSMostrarVehiculoResult) {
            this.WSMostrarVehiculoResult = WSMostrarVehiculoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSAlquilarCocheRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSAlquilarCoche", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSAlquilarCocheRequestBody Body;
        
        public WSAlquilarCocheRequest() {
        }
        
        public WSAlquilarCocheRequest(AppEscritorio.WSServicios.WSAlquilarCocheRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSAlquilarCocheRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ff;
        
        public WSAlquilarCocheRequestBody() {
        }
        
        public WSAlquilarCocheRequestBody(int idc, int idu, string fa, string ff) {
            this.idc = idc;
            this.idu = idu;
            this.fa = fa;
            this.ff = ff;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSAlquilarCocheResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSAlquilarCocheResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSAlquilarCocheResponseBody Body;
        
        public WSAlquilarCocheResponse() {
        }
        
        public WSAlquilarCocheResponse(AppEscritorio.WSServicios.WSAlquilarCocheResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class WSAlquilarCocheResponseBody {
        
        public WSAlquilarCocheResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSMostrarAlquileresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSMostrarAlquileres", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSMostrarAlquileresRequestBody Body;
        
        public WSMostrarAlquileresRequest() {
        }
        
        public WSMostrarAlquileresRequest(AppEscritorio.WSServicios.WSMostrarAlquileresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSMostrarAlquileresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idu;
        
        public WSMostrarAlquileresRequestBody() {
        }
        
        public WSMostrarAlquileresRequestBody(int idu) {
            this.idu = idu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSMostrarAlquileresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSMostrarAlquileresResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSMostrarAlquileresResponseBody Body;
        
        public WSMostrarAlquileresResponse() {
        }
        
        public WSMostrarAlquileresResponse(AppEscritorio.WSServicios.WSMostrarAlquileresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSMostrarAlquileresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppEscritorio.WSServicios.ArrayOfAlquilan WSMostrarAlquileresResult;
        
        public WSMostrarAlquileresResponseBody() {
        }
        
        public WSMostrarAlquileresResponseBody(AppEscritorio.WSServicios.ArrayOfAlquilan WSMostrarAlquileresResult) {
            this.WSMostrarAlquileresResult = WSMostrarAlquileresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSBuscarVehiculosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSBuscarVehiculos", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSBuscarVehiculosRequestBody Body;
        
        public WSBuscarVehiculosRequest() {
        }
        
        public WSBuscarVehiculosRequest(AppEscritorio.WSServicios.WSBuscarVehiculosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSBuscarVehiculosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string modelo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string combustible;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double precio;
        
        public WSBuscarVehiculosRequestBody() {
        }
        
        public WSBuscarVehiculosRequestBody(string modelo, string combustible, double precio) {
            this.modelo = modelo;
            this.combustible = combustible;
            this.precio = precio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSBuscarVehiculosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSBuscarVehiculosResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSBuscarVehiculosResponseBody Body;
        
        public WSBuscarVehiculosResponse() {
        }
        
        public WSBuscarVehiculosResponse(AppEscritorio.WSServicios.WSBuscarVehiculosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSBuscarVehiculosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppEscritorio.WSServicios.ArrayOfVehiculo WSBuscarVehiculosResult;
        
        public WSBuscarVehiculosResponseBody() {
        }
        
        public WSBuscarVehiculosResponseBody(AppEscritorio.WSServicios.ArrayOfVehiculo WSBuscarVehiculosResult) {
            this.WSBuscarVehiculosResult = WSBuscarVehiculosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSBuscarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSBuscarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSBuscarUsuarioRequestBody Body;
        
        public WSBuscarUsuarioRequest() {
        }
        
        public WSBuscarUsuarioRequest(AppEscritorio.WSServicios.WSBuscarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSBuscarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        public WSBuscarUsuarioRequestBody() {
        }
        
        public WSBuscarUsuarioRequestBody(string usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSBuscarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSBuscarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSBuscarUsuarioResponseBody Body;
        
        public WSBuscarUsuarioResponse() {
        }
        
        public WSBuscarUsuarioResponse(AppEscritorio.WSServicios.WSBuscarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSBuscarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AppEscritorio.WSServicios.usuario WSBuscarUsuarioResult;
        
        public WSBuscarUsuarioResponseBody() {
        }
        
        public WSBuscarUsuarioResponseBody(AppEscritorio.WSServicios.usuario WSBuscarUsuarioResult) {
            this.WSBuscarUsuarioResult = WSBuscarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSguardarCochesBDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSguardarCochesBD", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSguardarCochesBDRequestBody Body;
        
        public WSguardarCochesBDRequest() {
        }
        
        public WSguardarCochesBDRequest(AppEscritorio.WSServicios.WSguardarCochesBDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSguardarCochesBDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        public WSguardarCochesBDRequestBody() {
        }
        
        public WSguardarCochesBDRequestBody(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSguardarCochesBDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSguardarCochesBDResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSguardarCochesBDResponseBody Body;
        
        public WSguardarCochesBDResponse() {
        }
        
        public WSguardarCochesBDResponse(AppEscritorio.WSServicios.WSguardarCochesBDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class WSguardarCochesBDResponseBody {
        
        public WSguardarCochesBDResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSGuardarVehiculoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSGuardarVehiculo", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSGuardarVehiculoRequestBody Body;
        
        public WSGuardarVehiculoRequest() {
        }
        
        public WSGuardarVehiculoRequest(AppEscritorio.WSServicios.WSGuardarVehiculoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSGuardarVehiculoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string modelo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ano;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prestaciones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string color;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int puertas;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string combustible;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int valoracion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public double precio;
        
        public WSGuardarVehiculoRequestBody() {
        }
        
        public WSGuardarVehiculoRequestBody(string modelo, int ano, string prestaciones, string color, int puertas, string combustible, int valoracion, double precio) {
            this.modelo = modelo;
            this.ano = ano;
            this.prestaciones = prestaciones;
            this.color = color;
            this.puertas = puertas;
            this.combustible = combustible;
            this.valoracion = valoracion;
            this.precio = precio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSGuardarVehiculoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSGuardarVehiculoResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppEscritorio.WSServicios.WSGuardarVehiculoResponseBody Body;
        
        public WSGuardarVehiculoResponse() {
        }
        
        public WSGuardarVehiculoResponse(AppEscritorio.WSServicios.WSGuardarVehiculoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class WSGuardarVehiculoResponseBody {
        
        public WSGuardarVehiculoResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface serviciosSoapChannel : AppEscritorio.WSServicios.serviciosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class serviciosSoapClient : System.ServiceModel.ClientBase<AppEscritorio.WSServicios.serviciosSoap>, AppEscritorio.WSServicios.serviciosSoap {
        
        public serviciosSoapClient() {
        }
        
        public serviciosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public serviciosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviciosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviciosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEscritorio.WSServicios.WSRegistrarUsuarioResponse AppEscritorio.WSServicios.serviciosSoap.WSRegistrarUsuario(AppEscritorio.WSServicios.WSRegistrarUsuarioRequest request) {
            return base.Channel.WSRegistrarUsuario(request);
        }
        
        public void WSRegistrarUsuario(string nombre, string apellidos, int edad, string user, string pass) {
            AppEscritorio.WSServicios.WSRegistrarUsuarioRequest inValue = new AppEscritorio.WSServicios.WSRegistrarUsuarioRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSRegistrarUsuarioRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellidos = apellidos;
            inValue.Body.edad = edad;
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            AppEscritorio.WSServicios.WSRegistrarUsuarioResponse retVal = ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSRegistrarUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSRegistrarUsuarioResponse> AppEscritorio.WSServicios.serviciosSoap.WSRegistrarUsuarioAsync(AppEscritorio.WSServicios.WSRegistrarUsuarioRequest request) {
            return base.Channel.WSRegistrarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSRegistrarUsuarioResponse> WSRegistrarUsuarioAsync(string nombre, string apellidos, int edad, string user, string pass) {
            AppEscritorio.WSServicios.WSRegistrarUsuarioRequest inValue = new AppEscritorio.WSServicios.WSRegistrarUsuarioRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSRegistrarUsuarioRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellidos = apellidos;
            inValue.Body.edad = edad;
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSRegistrarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEscritorio.WSServicios.WSLoginResponse AppEscritorio.WSServicios.serviciosSoap.WSLogin(AppEscritorio.WSServicios.WSLoginRequest request) {
            return base.Channel.WSLogin(request);
        }
        
        public int WSLogin(string user, string pass) {
            AppEscritorio.WSServicios.WSLoginRequest inValue = new AppEscritorio.WSServicios.WSLoginRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSLoginRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            AppEscritorio.WSServicios.WSLoginResponse retVal = ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSLogin(inValue);
            return retVal.Body.WSLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSLoginResponse> AppEscritorio.WSServicios.serviciosSoap.WSLoginAsync(AppEscritorio.WSServicios.WSLoginRequest request) {
            return base.Channel.WSLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSLoginResponse> WSLoginAsync(string user, string pass) {
            AppEscritorio.WSServicios.WSLoginRequest inValue = new AppEscritorio.WSServicios.WSLoginRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSLoginRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEscritorio.WSServicios.WSMostrarVehiculosResponse AppEscritorio.WSServicios.serviciosSoap.WSMostrarVehiculos(AppEscritorio.WSServicios.WSMostrarVehiculosRequest request) {
            return base.Channel.WSMostrarVehiculos(request);
        }
        
        public AppEscritorio.WSServicios.ArrayOfVehiculo WSMostrarVehiculos() {
            AppEscritorio.WSServicios.WSMostrarVehiculosRequest inValue = new AppEscritorio.WSServicios.WSMostrarVehiculosRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSMostrarVehiculosRequestBody();
            AppEscritorio.WSServicios.WSMostrarVehiculosResponse retVal = ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSMostrarVehiculos(inValue);
            return retVal.Body.WSMostrarVehiculosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSMostrarVehiculosResponse> AppEscritorio.WSServicios.serviciosSoap.WSMostrarVehiculosAsync(AppEscritorio.WSServicios.WSMostrarVehiculosRequest request) {
            return base.Channel.WSMostrarVehiculosAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSMostrarVehiculosResponse> WSMostrarVehiculosAsync() {
            AppEscritorio.WSServicios.WSMostrarVehiculosRequest inValue = new AppEscritorio.WSServicios.WSMostrarVehiculosRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSMostrarVehiculosRequestBody();
            return ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSMostrarVehiculosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEscritorio.WSServicios.WSMostrarVehiculoResponse AppEscritorio.WSServicios.serviciosSoap.WSMostrarVehiculo(AppEscritorio.WSServicios.WSMostrarVehiculoRequest request) {
            return base.Channel.WSMostrarVehiculo(request);
        }
        
        public AppEscritorio.WSServicios.vehiculo WSMostrarVehiculo(int idv) {
            AppEscritorio.WSServicios.WSMostrarVehiculoRequest inValue = new AppEscritorio.WSServicios.WSMostrarVehiculoRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSMostrarVehiculoRequestBody();
            inValue.Body.idv = idv;
            AppEscritorio.WSServicios.WSMostrarVehiculoResponse retVal = ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSMostrarVehiculo(inValue);
            return retVal.Body.WSMostrarVehiculoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSMostrarVehiculoResponse> AppEscritorio.WSServicios.serviciosSoap.WSMostrarVehiculoAsync(AppEscritorio.WSServicios.WSMostrarVehiculoRequest request) {
            return base.Channel.WSMostrarVehiculoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSMostrarVehiculoResponse> WSMostrarVehiculoAsync(int idv) {
            AppEscritorio.WSServicios.WSMostrarVehiculoRequest inValue = new AppEscritorio.WSServicios.WSMostrarVehiculoRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSMostrarVehiculoRequestBody();
            inValue.Body.idv = idv;
            return ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSMostrarVehiculoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEscritorio.WSServicios.WSAlquilarCocheResponse AppEscritorio.WSServicios.serviciosSoap.WSAlquilarCoche(AppEscritorio.WSServicios.WSAlquilarCocheRequest request) {
            return base.Channel.WSAlquilarCoche(request);
        }
        
        public void WSAlquilarCoche(int idc, int idu, string fa, string ff) {
            AppEscritorio.WSServicios.WSAlquilarCocheRequest inValue = new AppEscritorio.WSServicios.WSAlquilarCocheRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSAlquilarCocheRequestBody();
            inValue.Body.idc = idc;
            inValue.Body.idu = idu;
            inValue.Body.fa = fa;
            inValue.Body.ff = ff;
            AppEscritorio.WSServicios.WSAlquilarCocheResponse retVal = ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSAlquilarCoche(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSAlquilarCocheResponse> AppEscritorio.WSServicios.serviciosSoap.WSAlquilarCocheAsync(AppEscritorio.WSServicios.WSAlquilarCocheRequest request) {
            return base.Channel.WSAlquilarCocheAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSAlquilarCocheResponse> WSAlquilarCocheAsync(int idc, int idu, string fa, string ff) {
            AppEscritorio.WSServicios.WSAlquilarCocheRequest inValue = new AppEscritorio.WSServicios.WSAlquilarCocheRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSAlquilarCocheRequestBody();
            inValue.Body.idc = idc;
            inValue.Body.idu = idu;
            inValue.Body.fa = fa;
            inValue.Body.ff = ff;
            return ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSAlquilarCocheAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEscritorio.WSServicios.WSMostrarAlquileresResponse AppEscritorio.WSServicios.serviciosSoap.WSMostrarAlquileres(AppEscritorio.WSServicios.WSMostrarAlquileresRequest request) {
            return base.Channel.WSMostrarAlquileres(request);
        }
        
        public AppEscritorio.WSServicios.ArrayOfAlquilan WSMostrarAlquileres(int idu) {
            AppEscritorio.WSServicios.WSMostrarAlquileresRequest inValue = new AppEscritorio.WSServicios.WSMostrarAlquileresRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSMostrarAlquileresRequestBody();
            inValue.Body.idu = idu;
            AppEscritorio.WSServicios.WSMostrarAlquileresResponse retVal = ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSMostrarAlquileres(inValue);
            return retVal.Body.WSMostrarAlquileresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSMostrarAlquileresResponse> AppEscritorio.WSServicios.serviciosSoap.WSMostrarAlquileresAsync(AppEscritorio.WSServicios.WSMostrarAlquileresRequest request) {
            return base.Channel.WSMostrarAlquileresAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSMostrarAlquileresResponse> WSMostrarAlquileresAsync(int idu) {
            AppEscritorio.WSServicios.WSMostrarAlquileresRequest inValue = new AppEscritorio.WSServicios.WSMostrarAlquileresRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSMostrarAlquileresRequestBody();
            inValue.Body.idu = idu;
            return ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSMostrarAlquileresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEscritorio.WSServicios.WSBuscarVehiculosResponse AppEscritorio.WSServicios.serviciosSoap.WSBuscarVehiculos(AppEscritorio.WSServicios.WSBuscarVehiculosRequest request) {
            return base.Channel.WSBuscarVehiculos(request);
        }
        
        public AppEscritorio.WSServicios.ArrayOfVehiculo WSBuscarVehiculos(string modelo, string combustible, double precio) {
            AppEscritorio.WSServicios.WSBuscarVehiculosRequest inValue = new AppEscritorio.WSServicios.WSBuscarVehiculosRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSBuscarVehiculosRequestBody();
            inValue.Body.modelo = modelo;
            inValue.Body.combustible = combustible;
            inValue.Body.precio = precio;
            AppEscritorio.WSServicios.WSBuscarVehiculosResponse retVal = ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSBuscarVehiculos(inValue);
            return retVal.Body.WSBuscarVehiculosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSBuscarVehiculosResponse> AppEscritorio.WSServicios.serviciosSoap.WSBuscarVehiculosAsync(AppEscritorio.WSServicios.WSBuscarVehiculosRequest request) {
            return base.Channel.WSBuscarVehiculosAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSBuscarVehiculosResponse> WSBuscarVehiculosAsync(string modelo, string combustible, double precio) {
            AppEscritorio.WSServicios.WSBuscarVehiculosRequest inValue = new AppEscritorio.WSServicios.WSBuscarVehiculosRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSBuscarVehiculosRequestBody();
            inValue.Body.modelo = modelo;
            inValue.Body.combustible = combustible;
            inValue.Body.precio = precio;
            return ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSBuscarVehiculosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEscritorio.WSServicios.WSBuscarUsuarioResponse AppEscritorio.WSServicios.serviciosSoap.WSBuscarUsuario(AppEscritorio.WSServicios.WSBuscarUsuarioRequest request) {
            return base.Channel.WSBuscarUsuario(request);
        }
        
        public AppEscritorio.WSServicios.usuario WSBuscarUsuario(string usuario) {
            AppEscritorio.WSServicios.WSBuscarUsuarioRequest inValue = new AppEscritorio.WSServicios.WSBuscarUsuarioRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSBuscarUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            AppEscritorio.WSServicios.WSBuscarUsuarioResponse retVal = ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSBuscarUsuario(inValue);
            return retVal.Body.WSBuscarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSBuscarUsuarioResponse> AppEscritorio.WSServicios.serviciosSoap.WSBuscarUsuarioAsync(AppEscritorio.WSServicios.WSBuscarUsuarioRequest request) {
            return base.Channel.WSBuscarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSBuscarUsuarioResponse> WSBuscarUsuarioAsync(string usuario) {
            AppEscritorio.WSServicios.WSBuscarUsuarioRequest inValue = new AppEscritorio.WSServicios.WSBuscarUsuarioRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSBuscarUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            return ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSBuscarUsuarioAsync(inValue);
        }
        
        public void WSguardarCochesXML() {
            base.Channel.WSguardarCochesXML();
        }
        
        public System.Threading.Tasks.Task WSguardarCochesXMLAsync() {
            return base.Channel.WSguardarCochesXMLAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEscritorio.WSServicios.WSguardarCochesBDResponse AppEscritorio.WSServicios.serviciosSoap.WSguardarCochesBD(AppEscritorio.WSServicios.WSguardarCochesBDRequest request) {
            return base.Channel.WSguardarCochesBD(request);
        }
        
        public void WSguardarCochesBD(string fileName) {
            AppEscritorio.WSServicios.WSguardarCochesBDRequest inValue = new AppEscritorio.WSServicios.WSguardarCochesBDRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSguardarCochesBDRequestBody();
            inValue.Body.fileName = fileName;
            AppEscritorio.WSServicios.WSguardarCochesBDResponse retVal = ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSguardarCochesBD(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSguardarCochesBDResponse> AppEscritorio.WSServicios.serviciosSoap.WSguardarCochesBDAsync(AppEscritorio.WSServicios.WSguardarCochesBDRequest request) {
            return base.Channel.WSguardarCochesBDAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSguardarCochesBDResponse> WSguardarCochesBDAsync(string fileName) {
            AppEscritorio.WSServicios.WSguardarCochesBDRequest inValue = new AppEscritorio.WSServicios.WSguardarCochesBDRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSguardarCochesBDRequestBody();
            inValue.Body.fileName = fileName;
            return ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSguardarCochesBDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEscritorio.WSServicios.WSGuardarVehiculoResponse AppEscritorio.WSServicios.serviciosSoap.WSGuardarVehiculo(AppEscritorio.WSServicios.WSGuardarVehiculoRequest request) {
            return base.Channel.WSGuardarVehiculo(request);
        }
        
        public void WSGuardarVehiculo(string modelo, int ano, string prestaciones, string color, int puertas, string combustible, int valoracion, double precio) {
            AppEscritorio.WSServicios.WSGuardarVehiculoRequest inValue = new AppEscritorio.WSServicios.WSGuardarVehiculoRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSGuardarVehiculoRequestBody();
            inValue.Body.modelo = modelo;
            inValue.Body.ano = ano;
            inValue.Body.prestaciones = prestaciones;
            inValue.Body.color = color;
            inValue.Body.puertas = puertas;
            inValue.Body.combustible = combustible;
            inValue.Body.valoracion = valoracion;
            inValue.Body.precio = precio;
            AppEscritorio.WSServicios.WSGuardarVehiculoResponse retVal = ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSGuardarVehiculo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSGuardarVehiculoResponse> AppEscritorio.WSServicios.serviciosSoap.WSGuardarVehiculoAsync(AppEscritorio.WSServicios.WSGuardarVehiculoRequest request) {
            return base.Channel.WSGuardarVehiculoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEscritorio.WSServicios.WSGuardarVehiculoResponse> WSGuardarVehiculoAsync(string modelo, int ano, string prestaciones, string color, int puertas, string combustible, int valoracion, double precio) {
            AppEscritorio.WSServicios.WSGuardarVehiculoRequest inValue = new AppEscritorio.WSServicios.WSGuardarVehiculoRequest();
            inValue.Body = new AppEscritorio.WSServicios.WSGuardarVehiculoRequestBody();
            inValue.Body.modelo = modelo;
            inValue.Body.ano = ano;
            inValue.Body.prestaciones = prestaciones;
            inValue.Body.color = color;
            inValue.Body.puertas = puertas;
            inValue.Body.combustible = combustible;
            inValue.Body.valoracion = valoracion;
            inValue.Body.precio = precio;
            return ((AppEscritorio.WSServicios.serviciosSoap)(this)).WSGuardarVehiculoAsync(inValue);
        }
    }
}
